# Appveyor, continuous integration for Windows
# https://ci.appveyor.com/project/nedbat/coveragepy

version: '{branch}-{build}'

build: off

shallow_clone: true

environment:

  PYTHON_PRERELEASE: ""
  WITH_COMPILER: "cmd /E:ON /V:ON /C .\\ci\\appveyor-with-compiler.cmd"

  matrix:
    - JOB: "2.6 32-bit"
      TOXENV: "py26"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python266"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "32"

    - JOB: "2.7 32-bit"
      TOXENV: "py27"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - JOB: "2.7 64-bit"
      TOXENV: "py27"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

    - JOB: "3.3 32-bit"
      TOXENV: "py33"
      WINDOWS_SDK_VERSION: "v7.1"
      PYTHON_HOME: "C:\\Python33"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "32"

    - JOB: "3.3 64-bit"
      TOXENV: "py33"
      WINDOWS_SDK_VERSION: "v7.1"
      PYTHON_HOME: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "64"

    - JOB: "3.4 32-bit"
      TOXENV: "py34"
      WINDOWS_SDK_VERSION: "v7.1"
      PYTHON_HOME: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - JOB: "3.4 64-bit"
      TOXENV: "py34"
      WINDOWS_SDK_VERSION: "v7.1"
      PYTHON_HOME: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

    # Meta coverage
    - JOB: "Meta 2.7"
      TOXENV: "py27"
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON_HOME: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      COVERAGE_COVERAGE: "yes"

    - JOB: "Meta 3.4"
      TOXENV: "py34"
      WINDOWS_SDK_VERSION: "v7.1"
      PYTHON_HOME: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      COVERAGE_COVERAGE: "yes"

init:
  - "ECHO %TOXENV%"

install:
  - "powershell ci\\appveyor-bootstrap.ps1"

test_script:
  - "%PYTHON_HOME%\\Scripts\\tox --version"
  - "%PYTHON_HOME%\\Scripts\\virtualenv --version"
  - "%PYTHON_HOME%\\Scripts\\pip --version"
  - "%WITH_COMPILER% %PYTHON_HOME%\\Scripts\\tox"

after_test:
  - if "%COVERAGE_COVERAGE%" == "yes" 7z a metacov-win-%TOXENV%.zip %APPVEYOR_BUILD_FOLDER%\.metacov*
  - if NOT "%COVERAGE_COVERAGE%" == "yes" %WITH_COMPILER% %PYTHON_HOME%\python setup.py bdist_wheel bdist_wininst

artifacts:
  - path: "dist\\*"
  - path: "metacov-*.zip"

notifications:
  - provider: Email
    to:
      - ned@nedbatchelder.com
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false
